jobs:
  include:
    - stage: mix test
      language: elixir
      elixir:
        - "1.8"
      otp_release:
        - "21.2"
      services:
        - postgresql
      before_script:
        - psql -c 'create database simplefootball_web_test;' -U postgres
        - cp config/travis.exs config/test.exs
        - mix do ecto.create, ecto.migrate
      script:
        - mix test

    - stage: mix dialyzer
      script:
        - mix dialyzer --halt-exit-status
      cache:
        directories:
          - priv/plts

    - stage: docker build
      script:
        - docker build -t lbproductions/simplefootball_web .
