language: elixir
elixir:
  - "1.8"
otp_release:
  - "21.2"

jobs:
  include:
    - stage: mix test
      services:
        - postgresql
      before_script:
        - sudo apt-get install -y rustc
        - psql -c 'create database simplefootball_web_test;' -U postgres
        - cp config/travis.exs config/test.exs
        - mix do ecto.create, ecto.migrate
      env:
        - MIX_ENV=test
      script:
        - mix coveralls.travis

    - stage: mix dialyzer
      before_script:
        - sudo apt-get install -y rustc
      script:
        - mix dialyzer --halt-exit-status
      cache:
        directories:
          - priv/plts

    - stage: docker build
      script:
        - docker build -t lbproductions/simplefootball_web .
