defmodule SimplefootballWeb.Lineup do
    use Ecto.Schema

    alias SimplefootballWeb.{Match, Team, LineupPlayer}
  
    @primary_key {:id, :binary_id, [autogenerated: false]}
    schema "lineups" do
        has_many(:lineup_players, LineupPlayer)
        has_many :starting, through: [:lineup_players, :player]
        has_many :bench, through: [:lineup_players, :player]
        belongs_to(:team, Team)
        belongs_to(:match, Match)
    end
end