defmodule SimplefootballWeb.Lineup do
    use Ecto.Schema

    alias SimplefootballWeb.{Match, Team, LineupPlayer}
  
    @primary_key {:id, :binary_id, [autogenerated: false]}
    schema "lineups" do
        has_many(:lineupPlayers, LineupPlayer)
        has_many :starting, through: [:lineupPlayers, :player]
        has_many :bench, through: [:lineupPlayers, :player]
        belongs_to(:team, Team)
        belongs_to(:match, Match)
    end
end