defmodule SimplefootballWeb.LineupPlayer do
    use Ecto.Schema

    alias SimplefootballWeb.{Player, Lineup}
  
    @primary_key {:id, :binary_id, [autogenerated: false]}
    schema "lineup_players" do
        belongs_to(:player, Player)
        belongs_to(:lineup, Lineup)
    end
end