defmodule SimplefootballWeb.MatchEvent do
    use Ecto.Schema
    import EctoEnum

    alias SimplefootballWeb.{Match}
    
    defenum MatchEventType, :matchEventType, [:goal, :substitution, :card]
  
    @primary_key {:id, :binary_id, [autogenerated: false]}
    schema "matchevents" do
        field(:matchEventType, MatchEventType)
        field(:minute, :integer)
        field(:isPenalty, :boolean, default: false)
        field(:isOwnGoal, :boolean, default: false)
        field(:isOvertime, :boolean, default: false)

        belongs_to(:match, Match)
    end
end