defmodule SimplefootballWeb.MatchEvent do
    use Ecto.Schema
    import EctoEnum

    alias SimplefootballWeb.{Match}
    
    defenum MatchEventType, :matchEventType, [:goal, :substitution, :card]
  
    @primary_key {:id, :binary_id, [autogenerated: false]}
    schema "match_events" do
        field(:match_event_type, MatchEventType)
        field(:minute, :integer)
        field(:is_penalty, :boolean, default: false)
        field(:is_owngoal, :boolean, default: false)
        field(:is_overtime, :boolean, default: false)

        belongs_to(:match, Match)
    end
end