defmodule SimplefootballWeb.Player do
    use Ecto.Schema
  
    @primary_key {:id, :binary_id, [autogenerated: false]}
    schema "players" do
        field(:name, :string)
        field(:shirt_number, :string)
        field(:tm_identifier, :string)
    end
end