defmodule SimplefootballWeb.Player do
    use Ecto.Schema
  
    @primary_key {:id, :binary_id, [autogenerated: false]}
    schema "players" do
        field(:name, :string)
        field(:shirtNumber, :string)
        field(:tmIdentifier, :string)
    end
end