defmodule SimplefootballWeb.Season do
    use Ecto.Schema

    alias SimplefootballWeb.{Competition, Matchday}
  
    @primary_key {:id, :binary_id, [autogenerated: false]}
    schema "seasons" do
        field(:year, :integer)

        belongs_to(:competition, Competition)
        has_many(:matchdays, Matchday)
    end
end