defmodule SimplefootballWeb.Team do
    use Ecto.Schema
  
    @primary_key {:id, :binary_id, [autogenerated: false]}
    schema "teams" do
        field(:name, :string)
        field(:abbreviation, :string)
        field(:alternative_names, {:array, :string})
        field(:tm_identifier, :string)
    end
end